### ISSUE TITLE
bug about  model.py

### ISSUE THREAD

**Issue by BelliumTang** [gzy-rgb/CauseRec#6]
Traceback (most recent call last):
  File "model.py", line 342, in <module>
    model.gen_dict(item_profile)
  File "model.py", line 54, in gen_dict
    self.embedding_layer(item_profile.to(self.device))]) 
RuntimeError: Expected object of scalar type Long but got scalar type Float for sequence element 1 in sequence argument at position #1 'tensors'

hello, 复现时遇到了这个bug，尝试过给item_profile转类型 .long() 依旧报错，输出item_profile查看的时候也是long型，并没有浮点数类型，很迷惑。

数据是从https://github.com/THUDM/ComiRec 下载的，但是里面是txt文件，然后转换成了csv

环境是python3.6，tensorflow-gpu1.8.0

希望得到解答，感谢感谢！

**Comment by ziqianglv** [comment]
Traceback (most recent call last):
  File "model.py", line 311, in <module>
    user_profile = list(set(ml_train['uid'].tolist()+ml_test['uid'].tolist()+ml_valid['uid'].tolist()))
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'uid'

hello，I ran into the keyerror problem and didn't know how to solve it, using a dataset that Tsinghua Cloud has already trained
